language: perl6

perl6:
  - 2018.01

os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y asciidoc

install:
  - rakudobrew build zef
  - zef install --deps-only --force-resolve .

script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t/
